More dreamhost compatibility
goodguyry/dreambox pull request #23
Opened 2017-02-08 07:20 UTC by jbtule

- added some more packages that are in dreamhost apt-get list on a shared plan (git & ruby.18) though not exhaustive
 - added a public folder on the variable config, many project types need a public subfolder to be hosted by apache rather than the full project root
 - synced folder can't chown root since NFS, modified vagrant file to add www-data
 - provision user based on dreambox_user_name, vagrant ssh then uses that user.

2017-02-22 23:23 UTC, PabloScolpino commented
+1 for this PR

2017-04-09 06:33 UTC, goodguyry commented
I agree!

I've been sidelined for a bit, but hoping to get back on this ASAP.

Thanks for the work on this, @jbtule! Sorry I left you hanging for so long.

2017-05-22 22:32 UTC, goodguyry requested changes
I'm sure you've tested this and it works fine for you, but I'm just wondering about the `esca` line. Thanks!

2017-05-22 22:32 UTC, goodguyry commented on files/user_setup
> +esca  echo
This is either a typo or some fancy Bash trick I'm not familiar with.

2017-05-22 22:32 UTC, goodguyry commented on templates/Vagrantfile
> +  if VAGRANT_COMMAND == "ssh"
Interesting! I was moving toward dropping the user creation stuff, but this may have just changed my mind.

2017-05-22 23:22 UTC, goodguyry commented on templates/Vagrantfile
> +      config.ssh.username = $user_vars['DREAMBOX_USER_NAME']
The indentation is off a bit here.

2017-05-24 05:12 UTC, goodguyry approved these changes

2017-05-24 05:12 UTC, merged